# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(793, 727)
        mainWindow.setStyleSheet("*:disabled {\n"
"    background-color:rgb(30, 30, 30);    \n"
"    color: rgb(127, 127, 127);\n"
"}\n"
"*{\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: white;\n"
"}\n"
"QLabel:disabled {\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(70, 70, 70);\n"
"    margin-top: 1em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QGroupBox:disabled {\n"
"    background-color: rgb(90, 90, 90);\n"
"}\n"
"QGroupBox::title {\n"
"    background-color: rgb(90, 90, 90);\n"
"        top: -0.8em;\n"
"        left: 1em;\n"
"}\n"
"QMenu::item{\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:selected{\n"
"    color: cyan;\n"
"}\n"
"QMenu::item:selected {\n"
"    color: cyan;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelQuestion = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQuestion.sizePolicy().hasHeightForWidth())
        self.labelQuestion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setObjectName("labelQuestion")
        self.horizontalLayout.addWidget(self.labelQuestion)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.row0 = QtWidgets.QHBoxLayout()
        self.row0.setObjectName("row0")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem10)
        self.btn0 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.row0.addWidget(self.btn0)
        self.btn1 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.row0.addWidget(self.btn1)
        self.btn3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.row0.addWidget(self.btn3)
        self.btn2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.row0.addWidget(self.btn2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row0.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.row0)
        self.row1 = QtWidgets.QHBoxLayout()
        self.row1.setObjectName("row1")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row1.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row1.addItem(spacerItem14)
        self.btn4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.row1.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.row1.addWidget(self.btn5)
        self.btn7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.row1.addWidget(self.btn7)
        self.btn6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.row1.addWidget(self.btn6)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row1.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row1.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.row1)
        self.row2 = QtWidgets.QHBoxLayout()
        self.row2.setObjectName("row2")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem18)
        self.btn12 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn12.setFont(font)
        self.btn12.setObjectName("btn12")
        self.row2.addWidget(self.btn12)
        self.btn13 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn13.setFont(font)
        self.btn13.setObjectName("btn13")
        self.row2.addWidget(self.btn13)
        self.btn15 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn15.setFont(font)
        self.btn15.setObjectName("btn15")
        self.row2.addWidget(self.btn15)
        self.btn14 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn14.setFont(font)
        self.btn14.setObjectName("btn14")
        self.row2.addWidget(self.btn14)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row2.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.row2)
        self.row3 = QtWidgets.QHBoxLayout()
        self.row3.setObjectName("row3")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem22)
        self.btn8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.row3.addWidget(self.btn8)
        self.btn9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.row3.addWidget(self.btn9)
        self.btn11 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn11.setFont(font)
        self.btn11.setObjectName("btn11")
        self.row3.addWidget(self.btn11)
        self.btn10 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.btn10.setFont(font)
        self.btn10.setObjectName("btn10")
        self.row3.addWidget(self.btn10)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem23)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row3.addItem(spacerItem24)
        self.verticalLayout.addLayout(self.row3)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem25)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem26)
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem27)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem28)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(mainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSee_online_help = QtWidgets.QAction(mainWindow)
        self.actionSee_online_help.setObjectName("actionSee_online_help")
        self.actionSee_offline_help = QtWidgets.QAction(mainWindow)
        self.actionSee_offline_help.setObjectName("actionSee_offline_help")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "K-Map Game"))
        self.labelQuestion.setText(_translate("mainWindow", "_"))
        self.btn0.setToolTip(_translate("mainWindow", "m0"))
        self.btn0.setText(_translate("mainWindow", "0"))
        self.btn1.setToolTip(_translate("mainWindow", "m1"))
        self.btn1.setText(_translate("mainWindow", "1"))
        self.btn3.setToolTip(_translate("mainWindow", "m3"))
        self.btn3.setText(_translate("mainWindow", "0"))
        self.btn2.setToolTip(_translate("mainWindow", "m2"))
        self.btn2.setText(_translate("mainWindow", "0"))
        self.btn4.setToolTip(_translate("mainWindow", "m4"))
        self.btn4.setText(_translate("mainWindow", "0"))
        self.btn5.setToolTip(_translate("mainWindow", "m5"))
        self.btn5.setText(_translate("mainWindow", "0"))
        self.btn7.setToolTip(_translate("mainWindow", "m7"))
        self.btn7.setText(_translate("mainWindow", "0"))
        self.btn6.setToolTip(_translate("mainWindow", "m6"))
        self.btn6.setText(_translate("mainWindow", "0"))
        self.btn12.setToolTip(_translate("mainWindow", "m12"))
        self.btn12.setText(_translate("mainWindow", "0"))
        self.btn13.setToolTip(_translate("mainWindow", "m13"))
        self.btn13.setText(_translate("mainWindow", "0"))
        self.btn15.setToolTip(_translate("mainWindow", "m15"))
        self.btn15.setText(_translate("mainWindow", "0"))
        self.btn14.setToolTip(_translate("mainWindow", "m14"))
        self.btn14.setText(_translate("mainWindow", "0"))
        self.btn8.setToolTip(_translate("mainWindow", "m8"))
        self.btn8.setText(_translate("mainWindow", "0"))
        self.btn9.setToolTip(_translate("mainWindow", "m9"))
        self.btn9.setText(_translate("mainWindow", "0"))
        self.btn11.setToolTip(_translate("mainWindow", "m11"))
        self.btn11.setText(_translate("mainWindow", "0"))
        self.btn10.setToolTip(_translate("mainWindow", "m10"))
        self.btn10.setText(_translate("mainWindow", "0"))
        self.actionSettings.setText(_translate("mainWindow", "App settings"))
        self.actionSee_online_help.setText(_translate("mainWindow", "See online help"))
        self.actionSee_offline_help.setText(_translate("mainWindow", "See offline help"))
